spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  thymeleaf:
    cache: false # 开发时关闭缓存
    mode: HTML
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 30MB

server:
  port: 8080

# 博客相关配置
blog:
  markdown:
    extensions: [AUTOLINK, TABLES]

jwt:
  secret: 8J6bZzqkRtA7X9LvMwYhN2PpQeFjHnKsDcV4BfGxTqWu3yJ5rCt0Oa1iEoUl+/M=
  expiration: 3600

# 静态资源映射
file:
  upload-dir: ${user.home}/Pictures/Bolg_BackEnd
  access-path: /images/**


# CORS配置
cors:
  allowed-origins: http://localhost:5173
  # 生产环境可以改为实际的域名
  # allowed-origins: https://your-production-domain.com
